2018-08-04 00:30:07,460 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 00:30:09,233 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 00:31:04,592 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 00:31:40,052 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 00:32:03,743 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 00:32:05,482 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 12:59:09,765 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 13:06:04,197 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 13:06:07,448 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 13:10:12,941 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 13:14:06,176 ERROR: Exception on /apiV2/ExpenseRes [GET] [in C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\api.py", line 323, in wrapper
    return self.make_response(data, code, headers=headers)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\api.py", line 344, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\representations.py", line 25, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "C:\ProgramData\Anaconda2\Lib\json\__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "C:\ProgramData\Anaconda2\Lib\json\encoder.py", line 209, in encode
    chunks = list(chunks)
  File "C:\ProgramData\Anaconda2\Lib\json\encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "C:\ProgramData\Anaconda2\Lib\json\encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "C:\ProgramData\Anaconda2\Lib\json\encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "C:\ProgramData\Anaconda2\Lib\json\encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte
2018-08-04 13:27:01,595 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 13:27:06,960 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 13:27:28,506 ERROR: Exception on /apiV2/ExpenseRes [POST] [in C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\views.py", line 83, in view
    self = view.view_class(*class_args, **class_kwargs)
TypeError: __init__() takes exactly 1 argument (2 given)
2018-08-04 13:28:38,030 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 13:29:19,121 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 13:29:29,996 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 13:29:31,674 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 13:29:40,392 ERROR: Exception on /apiV2/ExpenseRes [POST] [in C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\views.py", line 83, in view
    self = view.view_class(*class_args, **class_kwargs)
TypeError: __init__() takes exactly 1 argument (2 given)
2018-08-04 13:32:28,115 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 13:32:50,369 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 13:33:08,164 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 13:33:15,019 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 13:33:16,684 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 13:33:29,063 ERROR: Exception on /apiV2/ExpenseRes [POST] [in C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\views.py", line 83, in view
    self = view.view_class(*class_args, **class_kwargs)
TypeError: __init__() takes exactly 1 argument (2 given)
2018-08-04 13:34:32,901 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 13:34:34,688 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 13:34:38,315 ERROR: Exception on /apiV2/ExpenseRes [POST] [in C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\views.py", line 83, in view
    self = view.view_class(*class_args, **class_kwargs)
TypeError: __init__() takes exactly 1 argument (2 given)
2018-08-04 13:35:18,196 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 13:35:46,367 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 13:35:47,914 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 13:37:03,484 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-04 13:38:59,319 ERROR: Exception on /apiV2/ExpenseRes [GET] [in C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\api.py", line 323, in wrapper
    return self.make_response(data, code, headers=headers)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\api.py", line 344, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\representations.py", line 25, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "C:\ProgramData\Anaconda2\Lib\json\__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "C:\ProgramData\Anaconda2\Lib\json\encoder.py", line 209, in encode
    chunks = list(chunks)
  File "C:\ProgramData\Anaconda2\Lib\json\encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "C:\ProgramData\Anaconda2\Lib\json\encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "C:\ProgramData\Anaconda2\Lib\json\encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "C:\ProgramData\Anaconda2\Lib\json\encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte
2018-08-04 15:22:43,125 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
